# Site settings
title: Allen's Resume
description: My resume.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: "Allen Jia"
user_description: I'm proficient in using Python/SQL/R languages and Atom/Jupyter Notebook/Tableau softs to deal with data analysis issues. Now, I'm an assistant in Data Analysis Nano Degree of Udacity. And I'm a PLA ex-serviceman with strong self-control and implementation capacity.
user_title: Data Analyst(future)
email: allenjsj@163.com
github_username: CapAllen


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
